# https://taskfile.dev

version: '3'

vars:
  BINARY_FOLDER: bin
  BINARY_NAME: terraform-provider-influxdb-v2
  GOLANGCI_LINT_VERSION: v1.49.0
  VERSION: v0.4.2

dotenv: ['.env']

tasks:
  init:
    desc: Initialize for development
    cmds:
      - go install
      - go mod tidy
      - go mod vendor
  build:
    desc: Build the provider binary
    cmds:
      - go build -v -o {{.BINARY_FOLDER}}/{{.BINARY_NAME}}_{{.VERSION}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - '{{.BINARY_FOLDER}}/{{.BINARY_NAME}}_{{.VERSION}}'

  install:
    deps:
      - install-dev-override
      - build

  test:
    desc: Run unit tests
    cmds:
      - go test -tags=unit -v -cover ./...

  docs:
    desc: Update the generated documentation
    cmds:
      - go generate
    sources:
      - "main.go"
      - "influxdbv2/**/*.go"
      - "examples/**/*.tf"
      - go.mod
      - go.sum
    generates:
      - docs/**/*.md

  lint:
    desc: Run linters
    deps:
      - install-golangci-lint
    cmds:
      - golangci-lint run ./influxdbv2/...
    sources:
      - "influxdbv2\\**\\*.go"
      - go.mod
      - go.sum
      - .golangci.yml

  install-golangci-lint:
    desc: Install the golangci-lint tool
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - which golangci-lint
      - golangci-lint version | grep {{.GOLANGCI_LINT_VERSION}}

  install-dev-override:
    desc: Set up an override allowing a local version of the provider to be used
    cmds:
      - cmd: |
          cat << EOF > ~/.terraformrc
          provider_installation {
            dev_overrides {
              "registry.terraform.io/hasanhakkaev/influxdb-v2" = "$(pwd)/{{.BINARY_FOLDER}}"
            }
            direct {}
          }
          EOF
    status:
      - cat ~/.terraformrc | grep "$(pwd)/{{.BINARY_FOLDER}}"

  uninstall-dev-override:
    desc: Remove any local terraform overrides and binaries for local development
    cmds:
      - rm ~/.terraformrc
      - rm -rf ./bin